# Generated by Django 4.2.6 on 2023-11-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.CharField(max_length=500, null=True)),
                ('aid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.answers')),
                ('qid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.questions')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
    ]
