# Generated by Django 4.2.6 on 2023-11-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_aid_likes_answer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likes',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
    ]
