# Generated by Django 4.2.6 on 2023-11-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_likes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='like',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
    ]
