# Generated by Django 4.2.6 on 2023-11-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_answers_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='like',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
